<?

$associates_policy_blanks = array(

	'green_card'			=>	'is_gc',
	'blank_series'			=>	'sagr',
	'blank_number'			=>	'nagr',
	'policy_statuses_title'	=>	'status',	

);

$associates_accident_payments = array(

	'blank_series'			=>	'sagr',
	'blank_number'			=>	'nagr',
	'accidents_number'		=>	'n_ord_ic',
	'payment_date'			=>	'paym_date',
	'acts_amount'			=>	's_payed',
	'deleted'				=>	'is_del',
	'old_data'				=>	'IsOldData'

);

$associates_accidents = array(

	'blank_series'						=>	'sagr',
	'blank_number'						=>	'nagr',
	'accidents_number'					=>	'n_ord_ic',
	'accidents_date'					=>	'd_claim',
	'insurer_driver_identification_code'=>	'numb_flt',
	'driver'							=>	'name_flt',
	'driver_years_old'					=>	'age_flt',
	'driver_sex'						=>	'sex_flt',
	'driver_address'					=>	'addr_flt',
	'driver_licence_series'				=>	'ser_flt',
	'driver_licence_number'				=>	'docnum_flt',
	'auto'								=>	'auto_flt',
	'insurer_brand'						=>	'c_mark_flt',
	'insurer_model'						=>	'c_mod_flt',
	'insurer_sign'						=>	'reg_no_flt',
	'insurer_shassi'					=>	'vin_flt',
	'resolve_date'						=>	'd_close',
	'insurance'							=>	'refused',
	'amount_rough'						=>	's_decl',
	'acts_amount'						=>	's_paid',
	'regres'							=>	'regr',
	'fraud'								=>	'fraud',
	'owner_identification_code'			=>	'numb_vct',
	'owner_person_types_id'				=>	'pr_firm',
	'owner'								=>	'name_vct',
	'owner_resident'					=>	'resident',
	'owner_address'						=>	'addr_vct',
	'owner_years_old'					=>	'age_vct',
	'owner_sex'							=>	'sex_vct',
	//''									=>	'note',
	//'registration_accident_number'		=>	'reg_num',
	'accidents_datetime'				=>	'd_event',
	'accidents_address'					=>	'place_evnt',
	'assured_identification_code'		=>	'numb_vct2',
	'assured_person_types_id'			=>	'pr_firm2',
	'assured'							=>	'name_vct2',
	'assured_resident'					=>	'resident2',
	'assured_address'					=>	'addr_vct2',
	'property_types_id'					=>	'c_prop_type',
	'owner_brand'						=>	'c_mark_vct',
	'owner_model'						=>	'c_mod_vct',
	'marka'								=>	'auto_vct',
	'owner_sign'						=>	'reg_no_vct',
	'owner_shassi'						=>	'vin_vct',
	'risks_id'							=>	'c_risk',
	'victim_damage_note'				=> 	'risk_notes',
	'step_damage'						=>	'c_injury',
	'mvs'								=>	'is_euro',
	'accident_schemes_id'				=>	'c_event_s',
	'owner_insurance_company'			=>	'insurer_vct',
	'owner_blank_number'				=>	'nagr_vct',
	'owner_blank_series'				=>	'sagr_vct',
	'step_guilt'						=>	'degree_flt',
	'old_data'							=>	'IsOldData',
	'deleted'							=>	'is_del'

);

$associates_policies = array(

	'blank_series'						=>	'sagr',
	'blank_number'						=>	'nagr',
	'policy_statuses_title'				=>	'compl',
	'begin_datetime'					=>	'd_beg',
	'end_datetime'						=>	'd_end',
	'terms_title'						=>	'c_term',
	'policies_date'						=>	'd_distr',
	'terms_id1'							=>	'is_active1',	
	'terms_id2'							=>	'is_active2',
	'terms_id3'							=>	'is_active3',
	'terms_id4'							=>	'is_active4',
	'terms_id5'							=>	'is_active5',
	'terms_id6'							=>	'is_active6',
	'terms_id7'							=>	'is_active7',
	'terms_id8'							=>	'is_active8',
	'terms_id9'							=>	'is_active9',
	'terms_id10'						=>	'is_active10',
	'terms_id11'						=>	'is_active11',
	'terms_id12'						=>	'is_active12',
	'privileges'						=>	'c_privileg',
	'discount'							=>	'c_discount',
	'registration_regions_id'			=>	'zona',
	'bonus_malus'						=>	'b_m',
	'k1'								=>	'k1',
	'k2'								=>	'k2',
	'k3'								=>	'k3',
	'k4'								=>	'k4',
	'k5'								=>	'k5',
	'k6'								=>	'k6',
	'k7'								=>	'k7',
	'limit_life'						=>	'limit_life',
	'limit_property'					=>	'limit_prop',
	'deductible'						=>	'franchise',
	'amount_go'							=>	'payment',
	'payed_amount'						=>	'paym_bal',
	'comment'							=>	'note',
	'dissolved_date'					=>	'd_abort',
	'amount_return'						=>	'retpayment',
	'blank_series_parent'				=>	'chng_sagr',
	'blank_number_parent'				=>	'chng_nagr',
	'resident'							=>	'resident',
	'insurer_person_types_title'		=>	'status_prs',
	'insurer_identification_code'		=>	'numb_ins',
	'insurer_lastname'					=>	'f_name',
	'insurer_firstname'					=>	's_name',
	'insurer_patronymicname'			=>	'p_name',
	'insurer_dateofbirth'				=>	'birth_date',
	'insurer_phone'						=>	'phone',
	'insurer_passport'					=>	'doc_name',
	'insurer_passport_series'			=>	'doc_series',
	'insurer_passport_number'			=>	'doc_no',
	'insurer_zip'						=>	'post_code',
	'insurer_address'					=>	'address_e',
	//'registration_cities_id_mtsbu'			=>	'city',
	'registration_cities_id_mtsbu'			=>	'c_city',
	'item'								=>	'auto',
	'sign'								=>	'reg_no',
	'shassi'							=>	'vin',
	'car_types_title'					=>	'c_type',
	'brands_id'							=>	'c_mark',
	'models_id'							=>	'c_model',
	'brand'							=>	'mark_txt',
	'model'							=>	'model_txt',
	'year'								=>	'prod_year',
	'taxi'								=>	'sphere_use',
	'otk'								=>	'need_to',
	'otkdate'							=>	'date_next_to',
	'stage3'							=>	'c_exp',
	'old'								=>	'IsOldData'
	
);

?>