<?
/*
* Title: constants
*
* @author Eugene Cherkassky
* @email eugene.cherkassky@gmail.com
* @version 3.0
*/

define('ROLES_ADMINISTRATOR', 1);
define('ROLES_MANAGER', 2);
define('ROLES_MASTER', 4);
define('ROLES_AGENT', 8);
define('ROLES_CLIENT_CONTACT', 32);
define('ROLES_EXPERT', 128);

define('ACCOUNT_GROUPS_CAR_SERVICE',	-1);
define('ACCOUNT_GROUPS_COMPENSATION_HEAD', 1);
define('ACCOUNT_GROUPS_RECEPTIONIST', 2);
define('ACCOUNT_GROUPS_AVERAGE', 3);
define('ACCOUNT_GROUPS_ESTIMATE', 4);
define('ACCOUNT_GROUPS_ACCIDENT_CREATED', 12);
define('ACCOUNT_GROUPS_CONTACT_CENTER', 17);
define('ACCOUNT_GROUPS_ESTIMATE_HEAD',	24);
define('ACCOUNT_GROUPS_AVERAGE_HEAD', 25);
define('ACCOUNT_GROUPS_SERVICE_DEPARTMENT',	27);
define('ACCOUNT_GROUPS_MONITORING', 29);//Департамент врегулювання збитків, моніторинг
define('ACCOUNT_GROUPS_RECEPTIONIST_HEAD', 33);
define('ACCOUNT_GROUPS_WORK_WITH_NETWORK_CORPORATION', 37);
define('ACCOUNT_GROUPS_SETTLEMENT_EXPRESS',	44);

define('INSURANCE_COMPANIES_KNIAZHA',	1);
define('INSURANCE_COMPANIES_ORANTA',	2);
define('INSURANCE_COMPANIES_GENERALI',	3);
define('INSURANCE_COMPANIES_EXPRESS',	4);

define('AGENCIES_EXPRESS_INSURANCE',	1);
define('AGENCIES_KOLCEVAYA',	20);
define('AGENCIES_POLTAVA_AUTO',	37);

define('FINANCIAL_INSTITUTIONS_PROSTOFINANS', 18);
define('FINANCIAL_INSTITUTIONS_UKRAUTOLEASING', 35);

define('PAYMENT_STATUSES_NOT',	1);
define('PAYMENT_STATUSES_PARTIAL',	2);
define('PAYMENT_STATUSES_PAYED',	3);
define('PAYMENT_STATUSES_OVER',	4);

$PAYMENT_STATUSES = array(
	PAYMENT_STATUSES_NOT		=> 'не сплачено',
    PAYMENT_STATUSES_PARTIAL	=> 'частково сплачено',
    PAYMENT_STATUSES_PAYED		=> 'сплачено',
    PAYMENT_STATUSES_OVER		=> 'переплата');

define('PRODUCT_CORRECTION_FACTORS_TYPES_SPORTS', 1);
define('PRODUCT_CORRECTION_FACTORS_TYPES_AGES', 2);
define('PRODUCT_CORRECTION_FACTORS_TYPES_TERMS_HOURS', 3);
define('PRODUCT_CORRECTION_FACTORS_TYPES_PROFESSIONS', 4);
define('PRODUCT_CORRECTION_FACTORS_TYPES_LOCATION', 5);


define('PRODUCT_TYPES_AUTO', 1);
define('PRODUCT_TYPES_CARGO', 2);//Грузы
define('PRODUCT_TYPES_KASKO', 3);//КАСКО
define('PRODUCT_TYPES_GO', 4);//ОСАГО
define('PRODUCT_TYPES_DSKV', 6);//Добровільне страхування квартири та відповідальності
define('PRODUCT_TYPES_DGO', 7);//ДГО
define('PRODUCT_TYPES_CARGO_GENERAL', 8);//грузы, генеральные договора
define('PRODUCT_TYPES_CARGO_CERTIFICATE', 9);//сертифікат
define('PRODUCT_TYPES_DRIVE_GENERAL', 10);//перегон авто, генеральные договора
define('PRODUCT_TYPES_DRIVE_CERTIFICATE', 11);//перегон авто, сертифікат
define('PRODUCT_TYPES_PROPERTY',	12);//имущество
define('PRODUCT_TYPES_NS',	13);//несчастный случай
define('PRODUCT_TYPES_NS_TRANSPORT', 23);
define('PRODUCT_TYPES_GO_GENERAL',	14);//ОСАГО, генеральный договор
define('PRODUCT_TYPES_MORTAGE',	15);//ипотека
define('PRODUCT_TYPES_TRANSPORTER',	16);
define('PRODUCT_TYPES_THIRD_PARTY_LIABILITY',	17);
define('PRODUCT_TYPES_THIRD_PARTY_LIABILITY_PROF_RESP',	18);
define('PRODUCT_TYPES_TRANSPORT_ACCIDENTS',	19);
define('PRODUCT_TYPES_DANGER_OBJECTS',	20);
define('PRODUCT_TYPES_ONE_SHIPPING',	21);
define('PRODUCT_TYPES_DMS', 22);

define('PRODUCT_KASKO1',	138);//пакет «ЛЕГКИЙ»
define('PRODUCT_KASKO2',	139);//пакет «РОЗУМНИЙ»
define('PRODUCT_KASKO3',	140);//пакет «ПРЕМІУМ»

define('PRODUCT_KASKO_TESTDRIVE1',	142);//КАСКО.Тест Драйв.Тип1
define('PRODUCT_KASKO_TESTDRIVE2',	143);//КАСКО.Тест Драйв.Тип2
define('PRODUCT_KASKO_TESTDRIVE3',	144);//КАСКО.Тест Драйв.Тип3
define('PRODUCT_KASKO_TESTDRIVE4',	574);

define('PRODUCT_DOCUMENT_SECTIONS_SALE', 1);
define('PRODUCT_DOCUMENT_SECTIONS_SETTLEMENT', 2);

define('DOCUMENT_TYPES_POLICY_KASKO_APPLICATION', 1);
define('DOCUMENT_TYPES_POLICY_KASKO_AGREEMENT', 2);
define('DOCUMENT_TYPES_POLICY_KASKO_BILL', 3);
define('DOCUMENT_TYPES_POLICY_GO_POLICY1', 4);
define('DOCUMENT_TYPES_POLICY_GO_POLICY2', 5);
define('DOCUMENT_TYPES_POLICY_GO_BILL', 6);
define('DOCUMENT_TYPES_ACCIDENT_DECLARATION', 7);
define('DOCUMENT_TYPES_POLICY_PACKAGE', 25);
define('DOCUMENT_TYPES_POLICY_DSKV_APPLICATION', 26);
define('DOCUMENT_TYPES_POLICY_DSKV_AGREEMENT', 27);
define('DOCUMENT_TYPES_POLICY_DSKV_DESCRIPTION', 28);
define('DOCUMENT_TYPES_POLICY_CARGO_CERTIFICATEE', 31);
define('DOCUMENT_TYPES_POLICY_DRIVE_CERTIFICATE', 33);
define('DOCUMENT_TYPES_ACCIDENT_PHOTO_CAR', 36);//фото пошкодженого ТЗ
define('DOCUMENT_TYPES_ACCIDENT_INSURANCE_ACT', 37);
define('DOCUMENT_TYPES_ACCIDENT_REQUEST_BANK', 38);
define('DOCUMENT_TYPES_ACCIDENT_NOTE_PAYMENT', 39);//уже надо
define('DOCUMENT_TYPES_ACCIDENT_NOTE_EVACUATE',	40);
define('DOCUMENT_TYPES_ACCIDENT_REQUEST_GAI',	41);
define('DOCUMENT_TYPES_ACCIDENT_NOTE_EXPERTIZE',	42);
define('DOCUMENT_TYPES_ACCIDENT_NOTE_AGREEMENT',	43);
define('DOCUMENT_TYPES_POLICY_PROPERTY_AGREEMENT',	44);
define('DOCUMENT_TYPES_ACCIDENT_COMPETENT_AUTHORITIES',	48);
define('DOCUMENT_TYPES_ACCIDENT_DEFECTS',	50);
define('DOCUMENT_TYPES_ACCIDENT_PROTOCOL_REVIEW', 63);//протокол огляду
define('DOCUMENT_TYPES_ACCIDENT_INVOICE', 64);//рахунок-фактура
define('DOCUMENT_TYPES_POLICY_KASKO_QUESTIONNAIRE', 69);
define('DOCUMENT_TYPES_ACCIDENT_FRONT_PAGE',	71);//Титульный лист, КАСКО
define('DOCUMENT_TYPES_ACCIDENT_FRONT_PAGE_GO',	88);//Титульный лист, ЦВ
define('DOCUMENT_TYPES_ACCIDENT_REQUEST_CALCULATION',	75);//Службова записка на розрахунок вартості відновлювального ремонту
define('DOCUMENT_TYPES_ACCIDENT_GO_DECLARATION', 80); // ГО, Заявление,
define('DOCUMENT_TYPES_ACCIDENT_GO_PAYMENT_DECLARATION', 85); // ГО, Заявление на выплату
define('DOCUMENT_TYPES_ACCIDENT_INSURANCE_GO_ACT', 87); // ГО, Страховой акт
define('DOCUMENT_TYPES_ACCIDENT_COMPLETION_ACT', 89);//акт виконаних робіт
define('DOCUMENT_TYPES_ACCIDENT_REQUEST_CALCULATION_GO',	91);//Службова записка на розрахунок вартості відновлювального ремонту
define('DOCUMENT_TYPES_ACCIDENT_TOTAL_LETTER',	93);//Лист страхувальнику про тотал
define('DOCUMENT_TYPES_ACCIDENT_PROPERTY_APPLICATION', 96); // Майно, Заявление на выплату
define('DOCUMENT_TYPES_ACCIDENT_FRONT_PAGE_PROPERTY',	97);//Титульный лист, Майно
define('DOCUMENT_TYPES_ACCIDENT_INSURANCE_PROPERTY_ACT', 98);
define('DOCUMENT_TYPES_ACCIDENT_REQUEST_CHECK_RESEARCH_KASKO', 102);//службова записка на перевірку товарознавчого дослідження КАСКО
define('DOCUMENT_TYPES_ACCIDENT_REQUEST_CHECK_RESEARCH_GO', 103);//службова записка на перевірку товарознавчого дослідження ЦВ
define('DOCUMENT_TYPES_ACCIDENT_COMPROMISE_AGREEMENT_LETTER_KASKO',	109);
define('DOCUMENT_TYPES_ACCIDENT_REQUEST_COURT',	114);
define('DOCUMENT_TYPES_ACCIDENT_CONDUCTING_CARSCOMMODITY_RESEARCH_KASKO',	115);
define('DOCUMENT_TYPES_ACCIDENT_AUTOONLINE',	118);
define('DOCUMENT_TYPES_ACCIDENT_INSPECTION_CAR_KASKO',	119);
define('DOCUMENT_TYPES_ACCIDENT_CONDUCTING_CARSCOMMODITY_RESEARCH_GO',	120);
define('DOCUMENT_TYPES_ACCIDENT_INSPECTION_CAR_GO',	121);
define('DOCUMENT_TYPES_NOTIFICATION_PAYMENTS_GO',	146);
define('DOCUMENT_TYPES_ACCIDENT_NOTE_AGREEMENT_PROPERTY',	147);
define('DOCUMENT_TYPES_ACCIDENT_REQUEST_CALCULATION_PROPERTY',	150);
define('DOCUMENT_TYPES_ACCIDENT_REQUEST_VICTIM',	160);
define('DOCUMENT_TYPES_ACCIDENT_COMPROMISE_AGREEMENT_LETTER_PROPERTY',	162);
define('DOCUMENT_TYPES_ACCIDENT_DECLARATION_CARGO',	163);
define('DOCUMENT_TYPES_ACCIDENT_FRONT_PAGE_CARGO',	164);
define('DOCUMENT_TYPES_ACCIDENT_REQUEST_LETTER_INSURER_KASKO',	165);
define('DOCUMENT_TYPES_ACCIDENT_REQUEST_CALCULATION_CARGO',	167);
define('DOCUMENT_TYPES_ACCIDENT_NOTE_AGREEMENT_CARGO',	168);
define('DOCUMENT_TYPES_ACCIDENT_COMPROMISE_AGREEMENT_LETTER_CARGO',	169);
define('DOCUMENT_TYPES_ACCIDENT_INSURANCE_CARGO_ACT', 170);

define('DOCUMENT_TYPES_POLICY_NS_APPLICATION',	82);
define('DOCUMENT_TYPES_POLICY_NS_AGREEMENT',	83);
define('DOCUMENT_TYPES_POLICY_NS_QUESTIONNAIR',	78);

define('POLICY_CONTINUE_PERIOD',	'3 MONTH');
define('POLICY_CONTINUE_PERIOD2',	'6 MONTH');

define('TERMS_YEAR_GO', 25);
define('TERMS_YEAR_KASKO', 29);

define('POLICY_BLANK_STATUSES_CLEAR', 1);
define('POLICY_BLANK_STATUSES_USED', 2);
define('POLICY_BLANK_STATUSES_SPOILT', 3);
define('POLICY_BLANK_STATUSES_LOST', 4);

define('POLICY_TYPES_AGREEMENT', 1);//договор
define('POLICY_TYPES_QUOTE',	2);//запрос котировки

define('POLICY_STATUSES_CREATED', 1);//создан
define('POLICY_STATUSES_SENT', 2);//отправлен менеджеру
define('POLICY_STATUSES_ERROR', 3);//ошибки, менеджер отправляет клиенту
define('POLICY_STATUSES_RESENT', 4);//повторно направлен менеджеру
define('POLICY_STATUSES_REQUEST_QUOTE', 5);//запрос котировки к андеррайтеру
define('POLICY_STATUSES_REQUEST_QUOTE_ERROR', 6);//ошибка в запросе к андеррайтеру
define('POLICY_STATUSES_REQUEST_QUOTE_AGAIN', 7);//повторный запрос котировки к андеррайтеру
define('POLICY_STATUSES_QUOTE', 8);//котировка от андеррайтера
define('POLICY_STATUSES_REQUEST_AGREEMENT', 9);//запрос договора страхования
define('POLICY_STATUSES_GENERATED', 10);//полис страхования сформирован
define('POLICY_STATUSES_DISSOLVED', 11);//полис достроково припинено
define('POLICY_STATUSES_CANCELLED',	13);//полис анулирован, разобраться
define('POLICY_STATUSES_SPOILT',	14);//полис зіпсований для ГО
define('POLICY_STATUSES_COPY',	15);//полис дублікат для ГО
define('POLICY_STATUSES_CONTINUED',	16);//полис Пролонгований
define('POLICY_STATUSES_RENEW',	17);//полис Переукладений
define('POLICY_STATUSES_CONSULTATION',	18);//

define('POLICY_STATES_CONTINUED',	1);
define('POLICY_STATES_RENEW',	2);

$UNDERWRITING_POLICY_STATUSES = array(
POLICY_STATUSES_REQUEST_QUOTE,
POLICY_STATUSES_REQUEST_QUOTE_ERROR,
POLICY_STATUSES_REQUEST_QUOTE_AGAIN,
POLICY_STATUSES_QUOTE,
POLICY_STATUSES_REQUEST_AGREEMENT);

$CLIENT_FILL_POLICY_STATUSES = array(
POLICY_STATUSES_GENERATED,
POLICY_STATUSES_CONTINUED,
POLICY_STATUSES_RENEW);

define('ACCIDENT_APPLICATION_YEAR_LIMIT',	1900);

define('ACCIDENT_STATUSES_CHANGE_SECTION',	-1);
define('ACCIDENT_STATUSES_APPLICATION',	1);
define('ACCIDENT_STATUSES_CLASSIFICATION',	2);
define('ACCIDENT_STATUSES_INVESTIGATION',	3);
define('ACCIDENT_STATUSES_APPROVAL',	4);
define('ACCIDENT_STATUSES_PAYMENT',	5);
define('ACCIDENT_STATUSES_RESOLVED',	6);
define('ACCIDENT_STATUSES_RESET',	7);
define('ACCIDENT_STATUSES_REINVESTIGATION',	8);
define('ACCIDENT_STATUSES_DEFECTS',	9);
define('ACCIDENT_STATUSES_SUSPENDED',	10);
define('ACCIDENT_STATUSES_CLOSED',	11);
define('ACCIDENT_STATUSES_MTSBU',	12);
define('ACCIDENT_STATUSES_COMPROMISE_AGREEMENT',	13);
define('ACCIDENT_STATUSES_COMPROMISE_CONTINUE',	14);
define('ACCIDENT_STATUSES_TRANSFER_INSURANCE_COMPANY', 15);
define('ACCIDENT_STATUSES_COORDINATION', 16);
define('ACCIDENT_STATUSES_FAILED', 17);

define('ACCIDENT_INSURANCE_ACT_TYPE_FIRST_AMOUNT',	0);//Первая страховая выплата
define('ACCIDENT_INSURANCE_ACT_TYPE_EXTRA_CHARGE',	1);//Доплата
define('ACCIDENT_INSURANCE_ACT_TYPE_RETURNS_OTHER_DETAILS',	2);//Возврат денег на другие реквизиты
define('ACCIDENT_INSURANCE_ACT_TYPE_RETURN_AND_FAILURE',	3);//Возврат денег и отказ
define('ACCIDENT_INSURANCE_ACT_TYPE_RETURN_PARTIAL',	4);//Часткове повернення СВ за ВР

define('RECIPIENT_TYPES_OWNER',	1);
define('RECIPIENT_TYPES_ASSURED',	2);
define('RECIPIENT_TYPES_EXPERT',	3);
define('RECIPIENT_TYPES_INSURER',	4);
define('RECIPIENT_TYPES_CAR_SERVICE',	5);
define('RECIPIENT_TYPES_INSURED',	6);
define('RECIPIENT_TYPES_OTHER',	7);

define('PAYMENT_TYPES_EXPERTISE',	1);
define('PAYMENT_TYPES_EVACUATOR',	2);
define('PAYMENT_TYPES_COMPETENT_AUTHORITIES',	3);
define('PAYMENT_TYPES_PARKING',	4);
define('PAYMENT_TYPES_PART_PREMIUM',	5);
define('PAYMENT_TYPES_COMPENSATION',	6);

define('ACCIDENT_MESSAGE_TYPES_MESSAGE',	1);//Повідомлення
define('ACCIDENT_MESSAGE_TYPES_INSURER',	2);//Запит документів у страхувальника
define('ACCIDENT_MESSAGE_TYPES_OWNER',	3);//Запит документів у власника
define('ACCIDENT_MESSAGE_TYPES_ASSURED',	4);//Запит документів у вигодонабувач
define('ACCIDENT_MESSAGE_TYPES_DAI',	6);//Запит документів в ДАІ
define('ACCIDENT_MESSAGE_TYPES_BANK',	7);//Запит документів в банку
define('ACCIDENT_MESSAGE_TYPES_CALCULATION',	5);//Розрахунок суми відновлювального ремонту
define('ACCIDENT_MESSAGE_TYPES_CHECK_RESEARCH', 9);
define('ACCIDENT_MESSAGE_GET_ADMINISTRATION_MATERIALS',	10);
define('ACCIDENT_MESSAGE_TYPES_INSPECTION',	11);//Огляд ТЗ, для експертных організацій (справи ЦВ)
define('ACCIDENT_MESSAGE_TYPES_ACCIDENT_NUMBER_CALL',	12);//Повідомити номер справи
define('ACCIDENT_MESSAGE_TYPES_COPY_AGREEMENT', 13);//
define('ACCIDENT_MESSAGE_TYPES_RETURN_PART_COMPENSATION', 14);
define('ACCIDENT_MESSAGE_TYPES_CREATE_ADDITIONAL_AGREEMENT', 15);//Створити додаткову угоду
define('ACCIDENT_MESSAGE_TYPES_CONDUCTING_CARSCOMMODITY_RESEARCH', 16);
define('ACCIDENT_MESSAGE_TYPES_AUTOONLINE',	17);
define('ACCIDENT_MESSAGE_TYPES_VICTIM',	18);
define('ACCIDENT_MESSAGE_TYPES_REQUEST_COURT',	19);
define('ACCIDENT_MESSAGE_TYPES_REQUEST_VICTIM',	20);
define('ACCIDENT_MESSAGE_TYPES_REQUEST_LETTER_INSURER_KASKO',	21);
define('ACCIDENT_MESSAGE_TYPES_CAR_SERVICES_REQUEST',	22);  //Підтвердження термінів поставки ЗЧ

define('ACCIDENT_MESSAGE_STATUSES_QUESTION',	1);
define('ACCIDENT_MESSAGE_STATUSES_ANSWER',	2);
define('ACCIDENT_MESSAGE_STATUSES_ERROR',	3);
define('ACCIDENT_MESSAGE_STATUSES_INTERRUPTED',	4);
define('ACCIDENT_MESSAGE_STATUSES_COORDINATION',	5);
define('ACCIDENT_MESSAGE_STATUSES_APPROVAL',	6);

define('ACCIDENT_ARCHIVE_STATUSES_YES',	1);
define('ACCIDENT_ARCHIVE_STATUSES_NO',	0);

//денежные значения для условий отправки сообщений при класифицировании дел.
define('ACCIDENT_AMOUNT_ROUGH', 100000);
define('ACCIDENT_ITEMS_PRICE_MIDDLE', 150000);
define('ACCIDENT_ITEMS_PRICE_HIGH', 1000000);


define('COMMISSIONS_BASE_PRICE', 1);
define('COMMISSIONS_BASE_AMOUNT', 2);

$TRANSMISSIONS = array(
1 => 'механічна',
2 => 'автоматична');

$REGIONS = array(26, 27);

define('RISKS_DTP', 1);
define('RISKS_PDTO', 2);
define('RISKS_ACTOFGOD', 3);
define('RISKS_DOWNFALL', 4);
define('RISKS_ANIMAL', 5);
define('RISKS_FIRE1', 6);
define('RISKS_HIJACKING1', 7);
define('RISKS_FIRE2', 8);
define('RISKS_WATER', 9);
define('RISKS_HIJACKING2', 10);

define('CITIES_OTHER', 283);
define('CITIES_OUT_UKRAINE', 284);

define('CLIENTS_KGC', 3);
define('CLIENTS_AUTOCAPITAL', 4);
define('CLIENTS_AUTOZAZ', 8);
define('CLIENTS_ASKA_EXPEDITION', 9);

define('DELIVERY_WAYS_AUTO',	1);

define('NEWSLETTER_BLAST_SIZE', 20);
define('NEWSLETTER_BLAST_PAUSE', 5000);

define('CLIENT_GROUPS_UKRAUTO',	1);
define('CLIENT_GROUPS_OTHER',	2);

define('NDFL',	0.15);

define('E_IX_SYNHRONIZATION',	0); //1-вкл 0-выкл синхронизация со сторонней системой

define('EXPRESS_ASSISTANCE_STATUSES_NOT_USE',	1);
define('EXPRESS_ASSISTANCE_STATUSES_USE',	2);
define('ACCOUNT_BUH',	6631);
define('ACCOUNT_EI',	6559);

define('TASK_STATUSES_IN_WORK', 1);
define('TASK_STATUSES_CLOSED', 2);
define('TASK_STATUSES_CALL_NO', 1);
define('TASK_STATUSES_CALL_YES', 2);

define('TASK_TYPES_COMPENSATION_MESSAGE', 1);
define('TASK_TYPES_REPAIR', 2);

define('IMPORT_MTSBU_POLICIES',	3);
define('IMPORT_MTSBU_ACCIDENTS',	4);
define('IMPORT_MTSBU_POLICY_BLANKS',	7);
define('IMPORT_MTSBU_ACCIDENT_PAYMENTS',	57);

define('AMONT_PAYMENT_EUASSIST',	615);

define('AGENCY_SATIS',	1490);
define('SELLER_AGENCIES_ID',	1469);
define('SHOW_ACT_COMISSION',	1);
function cmp($a, $b) {
if (intval($a['orderpos']) == intval($b['orderpos'])) {
return 0;
}
return (intval($a['orderpos']) < intval($b['orderpos'])) ? -1 : 1;
}

?>