<div class="block">
    <table width="100%" cellspacing="0" cellpadding="0">
        <tr>
            <td class="bullet"><img src="/images/pixel.gif" width="1" height="1" alt="" /></td>
            <td class="caption">Звіти:</td>
        </tr>
        <tr>
            <td></td>
            <td>
                <table width="100%" cellspacing="0" cellpadding="0">
                    <tr><td height="4" bgcolor="#D6D6D6"><img src="/images/pixel.gif" width="1" height="1" alt="" /></td></tr>
                    <tr><td height="10"><img src="/images/pixel.gif" width="1" height="1" alt="" /></td></tr>
                    <tr>
                        <td valign="top">
                            <ul>
								<?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['showAccidentsReport']) ? '<li><a href="?do=Reports|showAccidentsReport">Врегулювання</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getSellAgencies']) ? '<li><a href="?do=Reports|getSellAgencies">Реалізація полiсiв по мiсяцях</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getSellChannels']) ? '<li><a href="?do=Reports|getSellChannels">Реалізація полiсiв по каналам</a><br /><br /></li>' : ''?>
								<?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getSellChannels']) ? '<li><a href="?do=Reports|getSellChannels3">Реалізація полiсiв Кредит/Рiтейл/Пролонгацiя</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getPoliciesGOSpecial']) ? '<li><a href="?do=Reports|getPoliciesGOSpecial">Реалізація полiсiв ЦВ. Акція</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getSellAgencies']) ? '<li><a href="?do=Reports|getSellFinancialInstitutions">Реалізація полiсiв за програмою "АВТОБАНК" (фізичні особи)</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getKASKOBordero']) ? '<li><a href="?do=Reports|getKASKOBordero&product_types_id=' . PRODUCT_TYPES_KASKO . '">КАСКО. Бордеро премій</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getCargoBordero']) ? '<li><a href="?do=Reports|getCargoBordero&product_types_id=' . PRODUCT_TYPES_CARGO . '">Сертифікати добровільного страхування вантажів та багажу (вантажобагажу). Бордеро премій.</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getCertificateCargoObjects']) ? '<li><a href="?do=Reports|getCertificateCargoObjects">Сертифікати добровільного страхування вантажів та багажу (вантажобагажу). Об\'єкти</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getPolicies']) ? '<li><a href="?do=Reports|getPolicies">Агентська винагорода, поліси</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getPoliciesGO']) ? '<li><a href="?do=Reports|getPoliciesGO">Агентська винагорода, поліси ЦВ</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getAkts']) ? '<li><a href="?do=Reports|getAkts">Агентська винагорода, акти виконанних робіт</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getInsuranceManagerActivity']) ? '<li><a href="?do=Reports|getInsuranceManagerActivity">Заборгованiсть агентів за полiсами КАСКО</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['InsurancePeriods']['show']) ? '<li><a href="?do=InsurancePeriods|show">Звiтнi перiоди</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['PaymentsCalendar']['show']) ? '<li><a href="?do=PaymentsCalendar|show">Платiжний календар</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getContinuePolicies']) ? '<li><a href="?do=Reports|getContinuePolicies">КАСКО, пролонгація по договорах</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getContinuePoliciesTotal']) ? '<li><a href="?do=Reports|getContinuePoliciesTotal">КАСКО, пролонгація за каналами продаж</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getContinuePoliciesRegions']) ? '<li><a href="?do=Reports|getContinuePoliciesRegions">КАСКО, пролонгація по регіонам</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getContinuePoliciesFinancialInstitutions']) ? '<li><a href="?do=Reports|getContinuePoliciesFinancialInstitutions">КАСКО, пролонгація по банкам</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getProductCounts']) ? '<li><a href="?do=Reports|getProductCounts">КАСКО, кiлькiсть продажiв по страховим продуктам</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getCardsAssistance']) ? '<li><a href="?do=Reports|getAssistance">Асiстанс, поліси страхування</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getPoliciesGOCompanies']) ? '<li><a href="?do=Reports|getPoliciesGOCompanies">ЦВ, реалізація полісів компаніями за період</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getBordereauReportedClaims']) ? '<li><a href="?do=Reports|getBordereauReportedClaims">Бордеро заявлених збитків</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getKaskoPolicies']) ? '<li><a href="?do=Reports|getKaskoPolicies">Каско для Богдана</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Akts']['show']) ? '<li><a href="?do=Akts|show">Акти</a><br /><br /></li>' : ''?>
								<?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['BankAkts']['show']) ? '<li><a href="?do=BankAkts|show">Акти банки</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['InsurancePlans']['show']) ? '<li><a href="?do=InsurancePlans|show">Плани</a><br /><br /></li>' : ''?>
								<?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['ReportBuilder']['show']) ? '<li><a href="?do=ReportBuilder|show">Отчеты</a><br /><br /></li>' : ''?>                                
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getPolicyBlanks']) ? '<li><a href="?do=Reports|getPolicyBlanks">Бланки полісів ЦВ</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getInsurancePremiums']) ? '<li><a href="?do=Reports|getInsurancePremiums">Страхові премії</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getXMLBanks']) ? '<li><a href="?do=Reports|getXMLBanks">Звіт для банків по договорам (XML)</a><br /><br /></li>' : ''?>                                
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getStatistics']) ? '<li><a href="?do=Reports|getStatistics">Статистика по ТЗ, витрати</a><br /><br /></li>' : ''?>
								<?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getStatistics']) ? '<li><a href="?do=Reports|getStatisticsByInsurancePeriods">Статистика по ТЗ (в розрізі страхових періодів)</a><br /><br /></li>' : ''?>
                                <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getCardAssistance']) ? '<li><a href="?do=Reports|getCardAssistance">Картки Ассістанс</a><br /><br /></li>' : ''?>                                
								<?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getPaymentsAndPremiums']) ? '<li><a href="?do=Reports|getPaymentsAndPremiums">Страхові відшкодування та страхові премії</a><br /><br /></li>' : ''?>								
								<?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getPaymentsDetails']) ? '<li><a href="?do=Reports|getPaymentsDetails">Вхідний та вихідний потоки (фінанси)</a><br /><br /></li>' : ''?>
								<?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getFinancialInstitutionsCommissions']) ? '<li><a href="?do=Reports|getFinancialInstitutionsCommissions">Комісія по договорах (Глушак Юлія)</a><br /><br /></li>' : ''?>
								
								<?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER && $Authorization->data['permissions']['Reports']['getExpressPolicies']) ? '<li><a href="?do=Reports|getExpressPolicies">Відділ продажу ТДВ "Експрес Страхування", поліси</a><br /><br /></li>' : ''?>
                            </ul>

                            <?=($Authorization->data['roles_id'] == ROLES_ADMINISTRATOR || $Authorization->data['roles_id'] == ROLES_MANAGER) ? '<a href="?do=Reports1|show">Нові звіти</a>' : ''?>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>